### ISSUE TITLE
Valida DNI como NIE

### ISSUE THREAD

**Issue by sergiober73** [coixinet/spain-id#2]
Acabo de probar que pasando un dni válido a validNIE() me devuelve true. Entiendo que no debería ser así. ¿Alguien me lo puede confirmar por favor?

**Comment by jvmonjo** [comment]
Hola. Esto ha sido solucionado en la próxima versión. Un saludo y gracias.

**Comment by sergiober73** [comment]
Funciona perfecto. Gracias!!!
